### ISSUE TITLE
IPv6 GO_POT__SERVER__HOST gets ignored

### ISSUE THREAD

**Issue by pr0ton11** [ryanolee/go-pot#1]
Hi

Great project, I would love to use it. Unfortunately I am in a IPv6 only environment.
I tried setting the GO_POT__SERVER__HOST to ``` [::]``` and ```::``` but it always gets set to ```0.0.0.0```

```
{"level":"info","ts":1717577423.0402246,"caller":"di/di.go:86","msg":"Starting server","port":8080,"host":"0.0.0.0"}
```

Could you help me with this issue?

**Comment by ryanolee** [comment]
Thanks for giving it a go @pr0ton11!

For the env var it is a very silly fix. Documented the prefix wrong. Should be `GOPOT__SERVER__HOST` not `GO_POT__SERVER__HOST` :melting_face: . Opened and merged https://github.com/ryanolee/go-pot/pull/3 to fix this.

IPV6 requires a few more changes. Opened a PR to fix the issue!
If you are able to could you clone the repo and checkout `feature/1` to see if it https://github.com/ryanolee/go-pot/pull/2) resolves your issue? (seem to work for me :eyes:) If it does will get it merged and draft a new release :partying_face: 
No worries of not though! Can just merge and draft a release.

**Comment by ryanolee** [comment]
For reference ` GOPOT__SERVER__NETWORK=tcp6` should enable tcp6 :eyes:

**Comment by pr0ton11** [comment]
Ok, seems to work here too. Worst case we just do another attempt here. I can confirm when it's running in my infra.
Btw. I am looking to use this to get insight into bot behavior. Maybe I'll open another PR to increase the metrics a bit. Would be good to have metrics, which files and endpoints have been accessed by whom.

**Comment by ryanolee** [comment]
Awesome will bundle a new release and mark this as done. Feel free to reopen this if you run into any further issues.

Any PR's are much welcomed! https://github.com/ryanolee/go-pot/blob/main/http/metrics/telemetry.go contains much of the logic surrounding tracing custom metrics. Might be worth looking  at https://github.com/ansrivas/fiberprometheus or similar for a good baseline :thinking:

**Comment by pr0ton11** [comment]
Tested it in my prod environment and works like a charm
