### ISSUE TITLE
Implement go lint

### ISSUE THREAD

**Issue by ryanolee** [ryanolee/go-pot#14]
# What
Implement go lint into CI https://github.com/golangci/golangci-lint-action.
Fix any low hanging / easy to fix CI errors.

# Why
Currently the quality of the code in the repository has not been fully vetted adding in a linter would go a long way towards catching any low hanging issues with the current platform.

**Comment by EdwinWalela** [comment]
@ryanolee I'm interested in picking this up. Go lint was [deprecated](https://github.com/golang/go/issues/38968) 4 years ago. [GolangCI](https://github.com/golangci/golangci-lint-action) seems like a good alternative. 

Do you have a preference of a CI library to be used?

**Comment by ryanolee** [comment]
Ohh thanks for taking a look! `golang-ci` seems great! Actually it is already in the repository under running `make lint`. Just not in CI! Don't worry if you don't get through the wall of linting issues as there are a fair few! Even adding it in so it runs on push would be a great help :tada:

**Comment by EdwinWalela** [comment]
From an initial lint run, the issues seem manageable (e.g unused functions and unchecked error return values). I should be able to handle the pipeline CI addition plus fixing the lint issues
